[package]
name = "notify-rust"
version = "3.1.1"
authors = ["Hendrik Sollich <hendrik@hoodie.de>", "panicbit <panicbit@users.noreply.github.com>"]
description = "Show desktop notifications. Similar to libnotify, with no gtk or Qt dependencies."
homepage = "https://github.com/hoodie/notify-rust"
repository = "https://github.com/hoodie/notify-rust"
documentation = "https://hoodie.github.io/notify-rust/"

license = "MIT/Apache-2.0"
keywords = ["desktop", "notification", "notify", "dbus", "libnotify"]
readme = "README.md"

[dependencies]
dbus = "~0.3"
clippy = {version = "*", optional = true}

[features]
default = []
dev = ["clippy"]
