[package]
name = "notify_send"
version = "0.0.4-dev"
authors = ["Hendrik Sollich <hendrik@hoodie.de>"]
description = "Sends DBus notifications, through dbus."
homepage = "https://github.com/hoodie/notify_send-rs"
repository = "https://github.com/hoodie/notify_send-rs"

license = "MIT/Apache-2.0"
keywords = ["desktop", "notify", "dbus"]
readme = "README.md"

[dependencies]
dbus = "0.0.9"
