[package]
name = "notify-rust"
version = "0.0.7-dev"
authors = ["Hendrik Sollich <hendrik@hoodie.de>"]
description = "Show desktop notifications. Similar to libnotify, but pure rust."
homepage = "https://github.com/hoodie/notify-rust"
repository = "https://github.com/hoodie/notify-rust"
documentation = "https://hoodie.github.io/notify-rust/"


license = "MIT/Apache-2.0"
keywords = ["desktop", "notification", "notify", "dbus", "libnotify"]
readme = "README.md"

[dependencies]
dbus = "0.1.0"
